version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=devdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
    command: > 
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - postgresqlnetwork

volumes:
  dev-static-data:

networks:
  postgresqlnetwork:
    external: true
